# Generated by Django 3.2.7 on 2021-09-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advuser',
            old_name='is_activate',
            new_name='is_activated',
        ),
    ]
